apiVersion: apps/v1
kind: Deployment
metadata:
  name: benchmark
spec:
  replicas: 3
  selector:
    matchLabels:
      app: benchmark
  template:
    metadata:
      labels:
        app: benchmark
    spec:
      containers:
        - name: benchmark
          image: deniscitadin/cmp270:3    
          ports:
            - containerPort: 8000
     
---
apiVersion: v1
kind: Service
metadata:
  name: benchmark
spec:
  selector:
    app: benchmark
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
